# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: trivy

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: Build
    runs-on: ubuntu-24.04-4core-150GB
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            ref: main
      - name: Read TAG from Makefile
        id: vars
        run: |
          TAG=$(grep -E '^TAG\s*[:?]?=' dine-in/Makefile | head -n1 | sed -E 's/^TAG\s*[:?]?=\s*//')
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
          
      - name: Build dine in image from Dockerfile
        run: |
            echo "running make build benchmark"
            cd dine-in
            make build REGISTRY=false
            
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1
        with:
            image-ref: "intel/order-accuracy-dine-in:${{ steps.vars.outputs.tag }}"
            format: 'table'
            severity: 'CRITICAL,HIGH'
            output: 'trivy-oa-dine-in-results.txt'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: actions/upload-artifact@v4
        with:
          name: trivy-order-accuracy-html-report
          path: trivy-oa-dine-in-results.txt
